### ISSUE TITLE
org.springframework.web.bind.annotation.RestController

### ISSUE THREAD

**Issue by wlnwl** [EmYiQing/WAF#1]
我没找到这个...

**Comment by wlnwl** [comment]
捂脸

**Comment by EmYiQing** [comment]
maven导入springboot-web这个模块，然后就不会有问题了。你查看下maven是否配置合适

**Comment by wlnwl** [comment]
关键我不让idea联网,不然激活就失效惹...捂脸

**Comment by wlnwl** [comment]
springboot啊...我导的spring...难怪

**Comment by EmYiQing** [comment]
不是导入，这个是maven项目，你仔细看一看怎么使用maven。不是传统SSM那种找到jar包，加入Build Path那种，是自动下载的。你不能断网。idea破解教程网上有一堆啊，你随便找个博客参照一下就好了。

**Comment by wlnwl** [comment]
我知道.

**Comment by wlnwl** [comment]
maven好久没用了...(我刚刚中考考完)

**Comment by wlnwl** [comment]
要不是idea要钱...捂脸
